#!/bin/bash

mkdir -p test/data

for full in manifests/*; do
    filename=$(basename $full)
    filename=${filename%.*}
    echo $filename

    if ! ./holen inspect $filename > test/data/${filename}.inspect; then
        echo "error running inspect for $filename"
        exit 1
    fi
done
