#!/usr/bin/env holen
---
desc: Freeze and thaw with Nippy at the command line
strategies:
    binary:
        base_url: https://github.com/justone/brisk/releases/download/v{{.Version}}/brisk-{{.OSArchData.tag}}.zip
        unpack_path: brisk
        os_arch:
            linux_amd64:
                tag: linux-amd64
            darwin_amd64:
                tag: macos-amd64
        versions:
          - version: '0.3.0'
            os_arch:
                linux_amd64:
                    sha256sum: b1cb87d610233586e3d62901726f51076dda3555434e49848b9e964bda57d6be
                darwin_amd64:
                    sha256sum: 39d3297225ffb1733b69d6b9a5f837c144f8e693b7295d005b3ae201f0e7a40a
          - version: '0.2.1'
            os_arch:
                linux_amd64:
                    sha256sum: 287e1830a7a539f5bb7c215d2e6f025eafe6954d37f8927a02868b4693ee6bd8
                darwin_amd64:
                    sha256sum: 6dfa8bb42c4ce23eed98fada97393cc7c49dab198a7e5efb467db5b3148942a4
          - version: '0.2.0'
            base_url: https://github.com/justone/brisk/releases/download/v{{.Version}}/brisk-{{.OSArchData.tag}}
            os_arch:
                linux_amd64:
                    sha256sum: 5422694ba6fb585ca47c7e1b4e39749d8d1620dad1f6757226e2b6a9dfe8863d
                darwin_amd64:
                    sha256sum: add539fcf19685b1c3139a9d86b109bb1141d443b1aa6d81d66f57032a459e0e
          - version: '0.1.0'
            os_arch:
                linux_amd64:
                    sha256sum: c4393ebc1f4adb75ee6226df53c887dece8ee8a94c4d0997e479713d36562f6c
                darwin_amd64:
                    sha256sum: b8839b202c1aa38ceab851facf6465172848a7182270fa31fb4b74c275f85ab1
