#!/usr/bin/env holen
---
desc: a diff that understands syntax
strategies:
    binary:
        base_url: https://github.com/Wilfred/difftastic/releases/download/{{.Version}}/difft-x86_64-{{.OSArchData.archtag}}.tar.gz
        unpack_path: difft
        os_arch:
            linux_amd64:
                archtag: unknown-linux-gnu
            darwin_amd64:
                archtag: apple-darwin
        versions:
          - version: '0.32.0'
            os_arch:
                linux_amd64:
                    sha256sum: d5a84f10b9e107048c1bafeab4f7320dd57948ffbd9cd13ff6b7c68bb986371f
                darwin_amd64:
                    sha256sum: ddcbb07bf3f563d37312456ac9fdae38d3d7499ab7dbda6923d9b242c37f2d6c
          - version: '0.28.0'
            os_arch:
                linux_amd64:
                    sha256sum: de5734c317a35d66a88dae14e2a021e7b24421a7937ce09c2674be71bed88c1f
                darwin_amd64:
                    sha256sum: ab890b24cb11da456c0fb0fd08e8d5d7bcf9140edd23b4641518e19f26271668
