#!/usr/bin/env holen
---
desc: 🌸  A command-line fuzzy finder written in Go
strategies:
    binary:
        base_url: https://github.com/junegunn/fzf/releases/download/{{.Version}}/fzf-{{.Version}}-{{.OSArch}}.{{.OSArchData.ext}}
        unpack_path: fzf
        os_arch:
            linux_amd64:
                ext: tar.gz
            darwin_amd64:
                ext: zip
        versions:
          - version: '0.34.0'
            os_arch:
                linux_amd64:
                    sha256sum: 312739b4774b0edbe1b83c971e3c6bb902b90773d3331553753e3eba34c684c9
                darwin_amd64:
                    sha256sum: 58700241743c712ca7f54e3caa63013ffe265af5e128aa77b90ffc045c3c5424
          - version: '0.17.5'
            base_url: https://github.com/junegunn/fzf-bin/releases/download/{{.Version}}/fzf-{{.Version}}-{{.OSArch}}.tgz
            os_arch:
                linux_amd64:
                    sha256sum: 3020c7d4d43d524ff394df306337b6de873b9db0bd9cd9dc73cd80cbd6e0c2f8
                darwin_amd64:
                    sha256sum: 0eaad771978823dac7e63fad4dfd2b324594240b1d8315941c95d56951eb28e7
          - version: '0.16.6'
            os_arch:
                linux_amd64:
                    sha256sum: ead4486b879fb91ae2c6e88ad4ad1bad5ed1e31fe02bc56489e289513f3a0f8f
                darwin_amd64:
                    sha256sum: f87da1a982719e8ba77d9cb16fc66fe941a67af6436b80d543d2894e218f9998
          - version: '0.15.9'
            unpack_path: fzf-{{.Version}}-{{.OSArch}}
            os_arch:
                linux_amd64:
                    sha256sum: 248799936c537a4d251ed73b859273416e5abc4bdcaea60ca73b78c75f6af7ac
                darwin_amd64:
                    sha256sum: 1cfba8d822e91126390f92662a5d560b59ff8830eade991cea9c6947a0be146f
