#!/usr/bin/env holen
---
desc: A Fast & Modern Static Website Engine, extended edition
strategies:
    binary:
        base_url: https://github.com/gohugoio/hugo/releases/download/v{{.Version}}/hugo_extended_{{.Version}}_{{.OSArchData.ext}}
        unpack_path: hugo
        os_arch:
            linux_amd64:
                ext: Linux-64bit.tar.gz
            darwin_amd64:
                ext: macOS-64bit.tar.gz
        versions:
          - version: '0.101.0'
            os_arch:
                linux_amd64:
                    sha256sum: 8c3adf2ace1604468325a6dd094bcc41c141c4a28a0c1ebbeb0022e714897595
                darwin_amd64:
                    sha256sum: 20388f56696d98362f7a6e1c8f3bfc622fddeff328640110a024713052a32b4d
          - version: '0.76.5'
            os_arch:
                linux_amd64:
                    sha256sum: 63443a8cd6d79d5698bcd403db84caf4c5bdcab184a71f45d9fbc94e9bc2922c
                darwin_amd64:
                    sha256sum: 5567699366c63c3084eb296c646a411f42ac9d1b44b3ff9250047495dfbb7bdb
          - version: '0.65.2'
            os_arch:
                linux_amd64:
                    sha256sum: 5c3b951610ddc3e5c43ca77601e3fd74d074ee8d85e14a26e7c27f20db8e6ec3
                darwin_amd64:
                    sha256sum: d53757533880c93b92f36a1eb1af680ffac3c514fd2d26a9885c107cd5455fc9
          - version: '0.49.2'
            os_arch:
                linux_amd64:
                    sha256sum: be6db985d1daf3494d317a3a7f9d30a43094d46c9a90c78724602d2ac0771c0f
                darwin_amd64:
                    sha256sum: 00bf013695cab81421cfabe6c8cbcb84276b679251f0dd0325c108fd84851786
