#!/usr/bin/env holen
---
desc: Personal Message Bus
strategies:
    binary:
        base_url: https://github.com/justone/pmb/releases/download/{{.Version}}/pmb_{{.OSArch}}{{.OSArchData.ext}}
        os_arch:
            windows_amd64:
                ext: .exe
        versions:
          - version: '2024-03-24-1449-7833ee7'
            os_arch:
                linux_amd64:
                    sha256sum: 9ad8f499d8cc1fc68795797bcd8fe766f868f48f9f9819c2425ddfb71a350fdb
                darwin_amd64:
                    sha256sum: 6b9d600f99860cada40b7b2a35f83ebd3bca59d85a345aa3e99a960576f88feb
                linux_arm64:
                    sha256sum: 04221066b6cc1ecb04768a6b3e0e507d0bbe6311b5d560366c334bfd3da2d32f
                darwin_arm64:
                    sha256sum: 97f1f87d2358100c0687c4b6e0b42f2a09bac0420509e472e1ad4df5cad82ed2
                windows_amd64:
                    sha256sum: 34715800c2fd4251a558ccecd5c5e6b0dcf60cc845a2d84dce9f5d0a72138153

...
